{{- if .Values.serviceAccount.create }}
{{- with .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: pact-broker
      {{- with .labels }}
      {{ toYaml . | trim | indent 8 }}
      {{- end }}
  {{- if .annotations }}
  annotations:
    {{- with .annotations }}
    {{ toYaml . | trim | indent 8 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{- if .imagePullSecrets }}
imagePullSecrets:
{{- range .imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
