{{- if .Values.serviceAccount.create }}
{{- with .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "broker.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: pact-broker
    {{- with .labels -}}
    {{ toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- with .annotations -}}
    {{ toYaml . | trim | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{- if .imagePullSecrets }}
imagePullSecrets:
{{- range .imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}